/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import game_mgr from "./script/game_mgr"
import home_mgr from "./script/home_mgr"
import hammer from "./script/hammer"
import score from "./script/score"
import main_mgr from "./script/main_mgr"
import over_mgr from "./script/over_mgr"
import ClickHideSelf from "./script/ClickHideSelf"
import mouse from "./script/mouse"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1080;
    static height:number=1920;
    static scaleMode:string="fixedauto";
    static screenMode:string="vertical";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="main_scence.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/game_mgr.ts",game_mgr);
        reg("script/home_mgr.ts",home_mgr);
        reg("script/hammer.ts",hammer);
        reg("script/score.ts",score);
        reg("script/main_mgr.ts",main_mgr);
        reg("script/over_mgr.ts",over_mgr);
        reg("script/ClickHideSelf.ts",ClickHideSelf);
        reg("script/mouse.ts",mouse);
    }
}
GameConfig.init();